model_name: POSTERv2

# dataset configs
dataset_name: AffectNetPlus
num_classes: 8
train_root: <DATASET_ROOT>/AffectNet+
val_root: <DATASET_ROOT>/AffectNet+
metadata: ~

# AffectNet+ loader options
affectnet_plus_label_mode: 8
affectnet_plus_use_soft_label: False
affectnet_plus_subsets: [0, 1, 2]
affectnet_plus_include_no_human: False
affectnet_plus_no_human_label_strategy: argmax
affectnet_plus_cache_index: True
affectnet_plus_cache_dir: "<DATASET_ROOT>/dataset_cache"
affectnet_plus_refresh_cache: False

train_frac: 1
val_frac: 1
sample_numbers: 6000
train_folds: [0]
val_folds: [1]
train_size: 224
val_size: 224
train_resize_size: 236
transforms_name: AFFECTNET_CUSTOM
train_shuffle: True
batch_size: 48
cache_img: False
update_freq: 1
eval_freq: 1
num_workers: 0
pretrained_timm: True
pretrained_local: ~
use_swanlab: False
use_wandb: False
log_root: results/teacher_logs

# optimizer configs
schedule_name: ExponentialLR
use_sam: True
rho: 0.05
optimizer: AdamW
init_lr: 0.00002
weight_decay: 0.0001
gamma: 0.9
max_epochs: 300
t_max: 300
use_amp: False

embedding_file: ~
loss_name: ce_kld_loss
ce_kld_beta: 0.001
metric_name: acc
metric_direction: up
valid_metrics: {"acc/valid": 0}
debug_after: {"train": 1000, "valid": 1000}
seed: 0
vae_head: False
vich_head: True
vich_use_sampling: True
vich_logvar_min: -10.0
vich_logvar_max: 10.0
vich_init_logvar_bias: 0.0
layer_embedding: True
votes_sum: 0
landmarks: 68
