model_name: POSTERv2
# dataset configs
dataset_name: FER2013
num_classes: 8

train_root: <DATASET_ROOT>/FERPlus_processed
val_root: <DATASET_ROOT>/FERPlus_processed
metadata: <DATASET_ROOT>/FERPlus_processed_metadata.csv
train_frac: 1
val_frac: 1
sample_numbers: 0
train_folds: [0,2]
val_folds: [1]
train_size: 224
val_size: 224
train_resize_size: 232
transforms_name: FERPLUS_CUSTOM
train_shuffle: True
batch_size: 48
cache_img: False
update_freq: 1
eval_freq: 1
num_workers: 0
pretrained_timm: False
pretrained_local: ~
log_root: results/teacher_logs
# optimizer configs
schedule_name: ExponentialLR
use_sam: True
rho: 0.05
optimizer: AdamW
init_lr: 0.00003
weight_decay: 0.0001
gamma: 0.96
max_epochs: 200
t_max: 200
use_amp: False
embedding_file: ~
loss_name: ce_kld_loss
ce_kld_beta: 0.001
metric_name: acc
metric_direction: up
valid_metrics: {'acc/valid': 0}
debug_after: {'train': 1000, 'valid': 1000}
seed: 0
vae_head: False
vich_head: True
vich_use_sampling: True
vich_logvar_min: -10.0
vich_logvar_max: 10.0
vich_init_logvar_bias: 0.0
layer_embedding: False
votes_sum: 1
landmarks: 68
